# Generated by Django 4.2 on 2026-02-01 04:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='protected/')),
                ('file_type', models.CharField(choices=[('PDF', 'PDF'), ('DOC', 'DOC'), ('NEWS', 'NEWS')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accessible_by', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
