# Generated by Django 5.2 on 2026-02-04 07:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('documents', '0002_companydocument_accessible_groups_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companydocument',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='companydocument',
            name='accessible_by',
            field=models.ManyToManyField(blank=True, help_text='Users who can view this document', related_name='documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='companydocument',
            name='accessible_groups',
            field=models.ManyToManyField(blank=True, help_text='Groups who can view this document', related_name='group_documents', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='companydocument',
            name='file_type',
            field=models.CharField(choices=[('PDF', 'PDF'), ('DOC', 'DOC'), ('DOCX', 'DOCX'), ('IMAGE', 'IMAGE'), ('NEWS', 'NEWS')], max_length=10),
        ),
    ]
