# Generated by Django 5.2 on 2026-03-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_remove_companydocument_file_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydocument',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='companydocument',
            name='author',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='companydocument',
            name='publication_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='companydocument',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
